### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by kenfager** [fstark/macflim#38]
Hello!

I've been meaning to try this since being wowed by it at Midwest Gaming Classic. I've downloaded the repository to my PiSCSI device and followed the installs for dependencies. When I try to make the file I'm getting an error.

```
pi@piscsi:~/macflim/src $ make
c++  -std=c++2a -c -O3 -I liblzg/src/include flimmaker.cpp -o flimmaker.o
In file included from flimcompressor.hpp:5,
                 from flimencoder.hpp:6,
                 from flimmaker.cpp:37:
framebuffer.hpp:7:10: fatal error: bit: No such file or directory
 #include <bit>
          ^~~~~
compilation terminated.
make: *** [Makefile:26: flimmaker.o] Error 1

```
Any guidance for someone who doesn't know C++ would be most appreciated.

-ken

**Comment by fstark** [comment]
Thx for the report, let's debug that.

This is strange as <bit> is a standard C++20 include.

However, I don't think I use the <bit> functions anymore, and removing the include from my version didn't break anything.

Can you remove the line #include <bit> from line 7 of ruler.hpp and tell me how it goes?

(but your C++ dev environment is wrong somewhere, so we may have other issues later)

**Comment by fstark** [comment]
Looking at another comment, it seems you standard library may be slightly outdated:

https://github.com/yuzu-emu/yuzu/issues/4780

Anyway, let me know if removing it works.

**Comment by fstark** [comment]
(removed the include in the latest commit, this issue should be fixed)
