### ISSUE TITLE
Add support for 720x364 and 608x431 resolutions for MacWorks

### ISSUE THREAD

**Issue by RebeccaRGB** [fstark/macflim#9]
MacWorks is a software package that allows an Apple Lisa to function as a Mac Plus with a larger screen.

In its stock configuration, the Lisa's screen has a resolution of 720x364 with a 2:3 pixel aspect ratio (pixels are 1.5 times taller than wide; the video would need to be stretched 1.5x horizontally or shrunk 0.666...x vertically to appear correctly).

There was an after-market modification available that gave the screen a resolution of 608x431 with square pixels. In this configuration the Lisa is called the Macintosh XL.

**Comment by fstark** [comment]
Note: with the latest beta (beta4) on the site or in the github .dsk, playback should work at those resolutions. Sound issues and performance are not addressed at all.

**Comment by fstark** [comment]
Latest version supports MacWorks 2 on the widget drive (using the ``--profile xl`` encoding option. Of course there are a lot of artifacts). Player needs a custom compilation, with FORCE_MINIMAL defined, as the run time discovery of System 2.x is not there yet, and the code call undefined traps.

See https://github.com/fstark/macflim/blob/5174ccbd9b8a8374c963e7e5ac56ad88111fd999/macsrc/Config.h#L10 for the place to change.
